OpenCOMPES/sed

.pre-commit-config.yaml
poetry.lock
sed/binning.py
sed/core.py
sed/metadata.py

This PR only adds code formatting and the pre-commit hooks file. Once reviewed and merged, I could start a more thorough refactoring of the code.

Code formatting

---

poetry.lock
pyproject.toml
sed/binning.py
tests/test_binning.py

I've made a generalization of the binning function. Now it can take any number of dimensions.
There are still a couple of details I'm not yet fully convinced:
- The name of the function: I personally do not like it but I kept the naming convention of the functions I replaced. Could we come up with something shorter or more descriptive?
- The way we have to pass the sample argument. Even if we want to calculate a 1D histogram, the sample has to be passed as a 2D array (np.array[[....],1]). I couldn't find a proper way to remove that and be compatible with Numba :(
Let me know what you think before merging.
P.S.: I've added also a couple of tests for that function.
P.S.2.: Sorry for the bad naming of the commit. I didn't squash them before pushing :(

Generalized histogram binning function

---

README.md
poetry.lock
pyproject.toml

I decided to create a PR to clarify what I meant by optional dependency. Please check the README here as well to see if this workflow makes sense or not. I personally think it makes sense thinking long term when we put this on PyPi, where SED will just be one package in the user's workflow. Let me know what you think.

Set jupyter and ipykernel as optional dependencies

---

.readthedocs.yaml
README.md

Added the config file for readthedocs webpage. The documentation can now be found on https://sed.readthedocs.io/en/latest/

Readthedocs config setup

---

README.md
env.yml

Adding the `env.yml` file to create conda environments. 
This was created by hand based on the requirements.txt file, but worked when tested.
This conda approach is, in my opinion, a simpler and more user-friendly approach, which will make the package more usable for non-expert users before we provide a packaged version.
Also, I updated the readme with the corresponding instructions.
Please let me know what you think, and if you have suggestions on how to make this conda/pip/poetry more intuitive and flexible. 
This pull request addresses issue #49

Setup requirements

---

sed/io.py

with recursive parsing of metadata dictionary
There certainly is a lot to improve, and this does not work for all data types in the metadata dictionary (some are converted to strings). We can generate multiple export/import functions. This is what we use currently to further convert to Nexus (we have a working pipeline for this).

xarray to h5 saving/loading functions 

---

sed/core.py
sed/diagnostic.py

This PR adds the histogram plotting functionality from mpes to the Core class.
Closes #4

Histogram plotting function

---

.github/workflows/pylint.yml

added github action for linting and testing

---

sed/loader/mpes/loader.py

fix timestamp bug in mpes-loader

---

sed/binning/numba_bin.py
tests/helpers.py
tests/test_binning.py
tutorial/Binning Benchmarks.ipynb

See #66 for details.
This initial commit contains additional test data to reproduce and test for the bug.

A PR to address the bug in numba binning

---

.github/workflows/pylint.yml
.github/workflows/pytest.yml
README.md
pyproject.toml
sed/binning/numba_bin.py
tests/helpers.py
tests/test_binning.py
tutorial/Binning Benchmarks.ipynb

Adds badges reporting test and linting status, as well as pypi package publishing status, and adds coverage support to the workflows

GitHub badges and coverage

---

sed/calibrator/momentum.py
sed/core/processor.py
tests/calibrator/test_momentum.py
tutorial/3 - Conversion Pipeline for example time-resolved ARPES data.ipynb

This PR separates the feature selection process from the spline generation step, and adds a GUI interface for that. It is based off the metadata branch, so this should be merged first, and then this branch be rebased (then there are only 3 files changed).

Point selector

---

sed/calibrator/energy.py
sed/core/processor.py
tests/calibrator/test_energy.py
tutorial/3 - Conversion Pipeline for example time-resolved ARPES data.ipynb

Interactive tool to select the TOF reference range for energy calibration. Mostly relevant for the MPES code so far.

Tof range selector

---

sed/config/default.yaml
sed/core/dfops.py
sed/core/processor.py
tests/test_processor.py

Also, add **kwds arguments to add_jitter

add default jitter axes to default config, and add tests for that. 

---

.github/dependabot.yml

The last test produced individual PRs for the indirect dependencies.
try dependency-type: all for groups

dependabot update

---

.github/dependabot.yml

remove any definition of the group

Dependabot test

---

sed/calibrator/energy.py

forgot to add the modifications before merging the PR

Fix save energy offset

---

sed/core/processor.py
tests/test_dfops.py
tests/test_processor.py

add the functionality to filter the dataframe to a range of values.
closes #13

add filter function in processor

---

.github/workflows/documentation.yml

increase remaining root space to 2GB

Improve documentation workflow

---

sed/core/config.py

Fixes a typo in the config library to allow running on windows

Fix system config path for Windows

---

sed/loader/flash/loader.py

Minor bug fix for wespe instrument at flash till we merge refactor branch

fix reference before assignment

---

.github/workflows/testing_coverage.yml
sed/core/processor.py
tests/test_processor.py

add option for either loading calibration data from file or from config
Closes #521

Delay calibration fixes

---

src/sed/core/logging.py
tests/test_logging.py

Closes #558 and adds logger tests

Logging tests and fixes

---

pyproject.toml
src/sed/config/NXmpes_config-HEXTOF.json
src/sed/config/NXmpes_config.json
tutorial/3_metadata_collection_and_export_to_NeXus.ipynb
tutorial/4_hextof_workflow.ipynb

Small updates to the nexus definitions, now very close to being officially standardized

update pynxtools version and adjust nexus config

---

src/sed/loader/mpes/metadata.py

Estimate temporal resolution from the pulse durations from elabFTW metadata if available

Calculate temporal resolution

---

src/sed/calibrator/momentum.py
src/sed/config/default.yaml
src/sed/core/processor.py
tests/calibrator/test_energy.py
tests/test_processor.py

Fix for the application of pose corrections without using a transformation. Also added a test for it.

Fix pose adjustment
