OpenCOMPES/sed

- tutorial/2 - Binning of example time-resolved ARPES data.ipynb
I added a notebook with test data on zenodo, please have a look. 
It requires the mpes package to generate the dataframe, and at the moment the version that is packaged cannot be installed together with sed (it pins h5py). I made a fork that does not do this at https://github.com/rettigl/mpes
Not sure if we should reflect this in the dependencies.
I intend to include this into the main mpes package, and maybe also make a new pypi package, but I don't really know how to do that.
I also did not thest with the new binning branch
> added tutorial notebook for example dataset

- sed/binning.py
- tests/test_binning.py
Implementing binning with arbitrary axes, allowing for non-linear binnings.
It works for bin_partition, but still not for bin_dataframe.
The reason is I am trying to use nBins as either the number of bins in the old method, but also to pass it arrays directly.
This then drops the requirement of binRanges. I will try fix this....
However the numba function works as of now, even if I had to use a workaround for the creation of the target nd-array.
I always hit this problem where you cannot create tuples in Numba.
@daviddoji if you can have a look at this would be great! the tutorial notebook has tests which use this new function.
> Arbitrary binning axes

- sed/core.py
- sed/dfops.py
- tests/test_binning.py
- tests/test_dfops.py
This pull request implements jittering on the intrinsic machine coordinates within the wrapper class by introducing a copy of the dataframe with jittering applied to the relevant coordinates. The idea would be to do this step in the beginning, and apply all following dataframe operations on both dataframes. Then, at the binning step, by choosing either dataframe, one can still choose between jitter or no jitter. Only downside is that this will be an all or nothing choice, depending on which axes one chose to be jitterd in the beginning.
The changes also include a first working version of binning in the wrapper class.
> Binning with jitter on machine coordinates

- sed/calibrator/hextof.py
- sed/core/dfops.py
- sed/core/processor.py
add the ability to run a rolled average on a column, based on acquisition time instead of on the direct rows. Useful for smoothing noisy channels.
> add rolling average and energy shift

- sed/config/default.yaml
- sed/core/processor.py
- tests/test_processor.py
- tutorial/Flash energy calibration.ipynb
- tutorial/config_flash_energy_calib.yaml
This PR is for developing energy calibration methods for flash. 
So far, it contains an example notebook on how to load the provided FLASH energy calibration run into the existing energy calibration workflow in the processor, and demonstrates how to use the existing energy calibration functions.
> Flash energy calibration

- .github/workflows/update_dependencies.yml
This should fix the problem in #256 by disabling the workflow for dependabot actions.
> ignore dependabot branches from triggering workflow

- .github/workflows/documentation.yml
- .github/workflows/release.yml
- .github/workflows/update_dependencies.yml
In reference to #285
Some comments in #280 are also addressed here
> Fix to release workflow

- .github/workflows/linting.yml
- sed/core/processor.py
- tests/test_processor.py
This implements a small unification of the code addressing #142
> unified typing of df_partitions

- sed/core/dfops.py
- sed/core/processor.py
- tests/test_dfops.py
- tests/test_processor.py
This PR adds the option to filter on the event index per partition, and adds a keyword parameter to the compute function to filter the dataframe on-the-fly during binning
> Add filter for index and on-the-fly filter

- .pre-commit-config.yaml
- sed/calibrator/delay.py
- sed/calibrator/energy.py
- sed/calibrator/momentum.py
- sed/core/processor.py
- sed/loader/mpes/loader.py
- tests/calibrator/test_delay.py
- tests/calibrator/test_energy.py
- tests/calibrator/test_momentum.py
- tests/test_processor.py
- tutorial/2_conversion_pipeline_for_example_time-resolved_ARPES_data.ipynb
This PR:
- unifies the interface for calibrations, corrections and offsets, and their saving and loading.
- adds time-stamps for the creation of the respective correction, and displays them when loading (optional).
- adds Saving/loading procedures for momentum transformations/pose adjustments 
closes #145 
closes #149
> Calibration creation date

- poetry.lock
- pyproject.toml
- sed/loader/flash/loader.py
- sed/loader/flash/metadata.py
- tests/loader/flash/test_flash_metadata.py
Suggested by @kutnyakhov in #345 , simple fix that only affects the flashloader so would be nice to merge quickly.
I will try to add tests, but might be tricky considering it's an API call.
> token based login for flash scicat

- sed/loader/flash/metadata.py
- tests/loader/flash/test_flash_metadata.py
Due to update of SciCat to a new backend at the beginning of the year, not only headers were changed but also URL was corrected (one "/" in front was removed).
Thus, it was possible to get only metadata ingested into SciCat this year using last PR #347 .
This PR now checking if "requests.get(new URL)" returns empty object and then uses instead "requests.get(old URL)".
> Get metadata from scicat using token

- sed/calibrator/momentum.py
replace scipy.interpolate.RegularGridInterpolator by scipy.ndimage.map_coordinates for a substantial improvement
of binning performance with momentum correction
Closes #357
> Improve interpolation performance

- docs/index.rst
- tutorial/8_jittering_tutorial.ipynb
> add notebook explaining the effect of jittering

- pyproject.toml
- sed/calibrator/energy.py
- sed/calibrator/momentum.py
- sed/loader/flash/loader.py
- sed/loader/generic/loader.py
- sed/loader/mpes/loader.py
- sed/loader/sxp/loader.py
- tests/loader/flash/test_flash_metadata.py
add linter options to check for unused arguments and variables, and add corresponding ignores
> Check for unused arguments and variables

- tests/test_binning.py
for tests/test_binning.py::test_normalization_histogram_from_timestamps
> raise tolorances to avoid random test failures 

- sed/binning/binning.py
- tests/test_binning.py
Several people have reported a bug per email with 
```
TypingError: Failed in nopython pipeline (step: nopython frontend)
non-precise type array (pyobject, 2d, F)
```
A quick fix was to just use hist_mode: numpy.
Now I finally managed to track it down to the cause. When the dtypes of different cols that are being binned are not the same, such as int16 and float32, numpy treats the array as a type object. 
Usually, numpy infers these types and choose the highest precision type for all in array automatically. However, if you do df.values, it is an object. But somehow choosing columns and then getting values makes numpy choose the array type correctly.
I also added an exception in case the array type is still an object.
> Exception handling for binning when df cols are of non-numeric types

- sed/core/metadata.py
- sed/core/processor.py
- tests/test_metadata.py
- tests/test_processor.py
This PR introduces an expandable representation of the data and metadata, and perhaps plots. We can discuss what should be included and what not.
Just type `sp` in a notebook after processor class has been instantiated and it will output the html version.
But also the metadata repr is interesting:
To test: you can write `sp.attributes` in a notebook and that will give the html representation.
If `print(sp.attributes)` is used, it gives a yaml representation, which is also more human readable than json.
closes #35
> Html representation of processor and metadata in notebooks

- benchmarks/benchmark_sed.py
- sed/core/dfops.py
- sed/loader/mpes/loader.py
This PR implements an alternative method to generate the per_file columns, which is much more performant.
Additionally, the function to add offsets is modified for a moderate speedup (removing the map_partitions call, and rather directly apply to the df columns)
> faster version of per_file channels

- .github/workflows/testing_coverage.yml
- .github/workflows/testing_multiversion.yml
- LICENSE
- docs/conf.py
- sed/__init__.py
- tests/test_sed.py
Currently after importing sed, typing `sed.__version__` gives 0.1.0 because it's been hardcoded. This PR should solve the issue.
> using importlib to get package version

- tests/data/loader/flash/config.yaml
- tests/loader/flash/conftest.py
- tests/loader/flash/test_buffer_handler.py
- tests/loader/flash/test_dataframe_creator.py
- tests/loader/flash/test_flash_loader.py
- tests/loader/flash/test_flash_metadata.py
- tests/loader/flash/test_utils.py
- tests/loader/test_loaders.py
Adds fixes for flash loader tests to run independently of local config files, and remove all intermediary parquet files.
> Flash test fixes

- .gitignore
- sed/binning/binning.py
- sed/calibrator/delay.py
- sed/calibrator/energy.py
- sed/config/default.yaml
- sed/config/flash_example_config.yaml
- sed/config/mpes_example_config.yaml
- sed/config/sxp_example_config.yaml
- sed/core/processor.py
- sed/loader/mirrorutil.py
- tests/calibrator/test_energy.py
- tutorial/5_sxp_workflow.ipynb
- tutorial/6_binning_with_time-stamped_data.ipynb
- tutorial/sxp_config.yaml
This changes the config behavior of tof_binning and adc_binning, as well as the config location of "num_cores"
closing #173 
closing #404
> Tof binning as actual binning values

- sed/config/flash_example_config.yaml
- tutorial/4_hextof_workflow.ipynb
Accidently reverted some changes that needed to be there.
Moreover, using the tutorial beamtime_id now because before it was set to the test data beamtime.
Additionally, the maxwell paths are provided instead of test data paths.
> Hextof tutorial missed out changes

- .github/workflows/testing_multiversion.yml
- poetry.lock
- pyproject.toml
- sed/__init__.py
The changes to the dfops in #411 allow to pass the tests with dask2024.6.2, however there are random failures during binning (see https://github.com/dask/dask/issues/11200). This requires further inspection.
> Update dask version

- sed/calibrator/momentum.py
- sed/core/processor.py
- tests/test_processor.py
Fix a problem with applying transformations from saved configuration without loading/generating a transformation slice, and add tests for this case.
> fix application of saved transformation, and add tests for this

- poetry.lock
- pyproject.toml
- sed/loader/mpes/loader.py
Adds exception handling for incomplete files that raise an IOError upon opening.
Closes #522
> Fix mpes incomplete files

- sed/loader/mpes/loader.py
Processing directly from the files for mpes is rather slow if reading from a filesystem with poor seeking performance (e.g. hdd, network drives). To overcome this, we load all files completely into memory for each binning step, and then access them from there.
> Mpes process files from memory

- src/sed/loader/mirrorutil.py
- src/sed/loader/mpes/loader.py
handling for filesystems without proper file xattributes.
These are mostly relevant if the last file cannot be opened at all, and e.g. for S3 storage systems mounted with rclone
> add further exceptions for completely empty files, and exceptions

- src/sed/core/config.py
- tests/test_config.py
> Pydantic error handling

- .cspell/custom-dictionary.txt
- src/sed/core/config.py
- tests/test_config.py
> update tests for env variables

- .github/workflows/documentation.yml
- pyproject.toml
- Update GitHub Actions workflow for documentation: Don't set pre-releases as stable
- Modify pyproject.toml for release adjustments
> Fix release and update documentation

- docs/user_guide/config.md
- src/sed/core/config.py
- tests/test_config.py
change user and system config files to config_v1.yaml add system wide .env
> use user platformdir also for user config

- src/sed/binning/binning.py
- src/sed/core/processor.py
- tests/test_processor.py
Sets the dtype of normalized data to that of unnormalized data.
Currently, it gets the dtype of the normalization histogram
> Fix normed dtype
